import colors from 'tailwindcss/colors';

const configuration = {
    colors: {
        background:         'var(--color-background)',
        foreground:         'var(--color-foreground)',
        accent:             'var(--color-accent)',
        active:             'var(--color-active)',
        variant:            'var(--color-variant)',
        surface:            'var(--color-surface)',
    },
    backgroundColor: {
        'surface-1':        'var(--color-surface-1)',
        'surface-2':        'var(--color-surface-2)',
        'surface-3':        'var(--color-surface-3)',
        'surface-4':        'var(--color-surface-4)',
        'surface-5':        'var(--color-surface-5)',
    },
    borderColor: {
        DEFAULT:            'rgb(var(--color-border))',
        divide:             'rgb(var(--color-divide))',
        line:               'rgb(var(--color-line))',
    },
    divideColor: {
        DEFAULT:            'rgb(var(--color-divide))',
        border:             'rgb(var(--color-border))',
        line:               'rgb(var(--color-line))',
    },
    ringColor: {
        DEFAULT:            'rgb(var(--color-ring))',
        border:             'rgb(var(--color-border))',
        outline:            'rgb(var(--color-outline))',
    },
    outlineColor: {
        DEFAULT:            'rgb(var(--color-outline))',
        border:             'rgb(var(--color-border))',
        divide:             'rgb(var(--color-divide))',
        line:               'rgb(var(--color-line))',
    },
    textColor: {
        heading:            'rgb(var(--color-text-heading))',
        default:            'rgb(var(--color-text-default))',
        subtle:             'rgb(var(--color-text-subtle))',
        muted:              'rgb(var(--color-text-muted))',
        disabled:           'rgb(var(--color-text-disabled))',
        hint:               'rgb(var(--color-text-hint))',
        icon: {
            heading:        'rgb(var(--color-icon-heading))',
            default:        'rgb(var(--color-icon-default))',
            subtle:         'rgb(var(--color-icon-subtle))',
            muted:          'rgb(var(--color-icon-muted))',
            disabled:       'rgb(var(--color-icon-disabled))',
            hint:           'rgb(var(--color-icon-hint))',
        },
    },
    fill: {
        icon: {
            heading:        'rgb(var(--color-icon-heading))',
            default:        'rgb(var(--color-icon-default))',
            subtle:         'rgb(var(--color-icon-subtle))',
            muted:          'rgb(var(--color-icon-muted))',
            disabled:       'rgb(var(--color-icon-disabled))',
            hint:           'rgb(var(--color-icon-hint))',
        },
        outline: 'rgb(var(--color-outline))',
        border: 'rgb(var(--color-border))',
        divide: 'rgb(var(--color-divide))',
        line: 'rgb(var(--color-line))',
    },
    stroke: {
        icon: {
            heading:        'rgb(var(--color-icon-heading))',
            default:        'rgb(var(--color-icon-default))',
            subtle:         'rgb(var(--color-icon-subtle))',
            muted:          'rgb(var(--color-icon-muted))',
            disabled:       'rgb(var(--color-icon-disabled))',
            hint:           'rgb(var(--color-icon-hint))',
        },
        outline: 'rgb(var(--color-outline))',
        border: 'rgb(var(--color-border))',
        divide: 'rgb(var(--color-divide))',
        line: 'rgb(var(--color-line))',
    },
    fontFamily: {
        brand:              'var(--font-brand)',
        content:            'var(--font-content)',
        decoration:         'var(--font-decoration)',
        code:               'var(--font-code)',
        digits:             'var(--font-digits)',
        display:            'var(--font-display)',
        heading:            'var(--font-heading)',
        body:               'var(--font-body)',
        caption:            'var(--font-caption)',
        label:              'var(--font-label)',
        control:            'var(--font-control)',
        button:             'var(--font-button)',
    },
    borderRadius: {
        none:               'var(--rounded-none)',
        xs:                 'var(--rounded-xs)',
        sm:                 'var(--rounded-sm)',
        DEFAULT:            'var(--rounded-DEFAULT)',
        md:                 'var(--rounded-md)',
        lg:                 'var(--rounded-lg)',
        xl:                 'var(--rounded-xl)',
        '2xl':              'var(--rounded-2xl)',
        '3xl':              'var(--rounded-3xl)',
        full:               'var(--rounded-full)',

        image:              'var(--rounded-image)',
        picture:            'var(--rounded-picture)',
        thumbnail:          'var(--rounded-thumbnail)',
        avatar:             'var(--rounded-avatar)',

        input:              'var(--shape-input)',
        control:            'var(--shape-control)',
        button:             'var(--shape-button)',
        handler:            'var(--shape-handler)',
        card:               'var(--shape-card)',
        dropdow:            'var(--shape-dropdow)',
        popover:            'var(--shape-popover)',
        moda:               'var(--shape-modal)',
        aler:               'var(--shape-alert)',
        toolbar:            'var(--shape-toolbar)',
        tooltip:            'var(--shape-tooltip)',

        option:             'var(--shape-option)',

        header:             'var(--shape-header)',
        footer:             'var(--shape-footer)',
        sidebar:            'var(--shape-sidebar)',
        content:            'var(--shape-content)',
    },
    borderWidth: {
        DEFAULT:            'var(--border-width)',
        none:               'var(--border-width-none)',
        sm:                 'var(--border-width-sm)',
        md:                 'var(--border-width-md)',
        lg:                 'var(--border-width-lg)',
    }
}

export default configuration;
